### ISSUE TITLE
Application compatibility mode is active. Disable it for this application

### ISSUE THREAD

**Issue by Aholicknight** [arielkoren/DisablePatchGuard#7]
I am running Windows 10 x64 in a virtual machine. I run patch.exe as admin and this pops up:
![image](https://user-images.githubusercontent.com/7843719/152660544-7f859165-7f87-4cc3-802e-e8bca1c33d2b.png)

When I check the compatibility settings for the exe, nothing is checkmarked
![vmware_4465216636](https://user-images.githubusercontent.com/7843719/152660555-9ffdd40b-f835-4a5d-8e02-06fd3b9147a6.png)

How can I fix this?

**Comment by matt-src** [comment]
Same issue here. Ever find a solution?

**Comment by Aholicknight** [comment]
Can't remember what I did you fix this problem, sorry
